
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VybmFtZSI6IkFuZ2dhIiwiZXhwIjoxNjU1MzE2NDc0fQ.1oUFobA606b3g6KrA8D-NDpN9SKd9YS6xzrmWYhk4j8
### GET DATA USER WITH AUTH
GET  http://localhost:8080/user/ HTTP/1.1
Authorization: Bearer {{token}}

###LOGIN
POST http://localhost:8080/auth/ HTTP/1.1
Content-Type: application/json

{
    "username" : "Angga",
    "password" : "abcd123123456"
}

###GET VEHICLE NO AUTH
GET  http://localhost:8080/vehicle/ HTTP/1.1
Content-Type: application/json

### CREATE USER
POST http://localhost:8080/user/ HTTP/1.1
Content-Type: application/json

{
    "username" : "user4",
    "password" : "abcd123123456",
    "email": "hallo@gmail.com",
    "phone": "0895867456"
    

}
###UPDATE USER
PUT  http://localhost:8080/user/update?id=11 HTTP/1.1
Content-Type: application/json

{
    "username" : "NAMABARU",
    "password" : "123455",
    "email"    : "ardhinataangga@gmail.com",
    "phone"    : "085764904549"

}
### DELETE
DELETE http://localhost:8080/user/4 HTTP/1.1
Content-Type: application/json

### CREATE Vehicle
POST http://localhost:8080/vehicle/ HTTP/1.1
Content-Type: application/json

{
    "name"      : "Lamborgini",
    "type"      : "Sport Car",
    "price"      : "20000"
    
}

### CREATE ORDER
POST http://localhost:8080/order/ HTTP/1.1
Content-Type: application/json

{
    "userid" : "1",
    "vehicle_id" : "1"
    

}


### GET ORDER BY ORDER ID
GET http://localhost:8080/order/1 HTTP/1.1
Content-Type: application/json
